#
server:
  port: 80
  session-timeout: 1800
#
spring:
  profiles:
      active: dev
  messages:
      basename: i18n/messages
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 10Mb
#
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  type-aliases-package: com.cit.web.**.entity
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
# swagger
swagger:
  enabled: true
  base-package: com.cit.web
  title: Webboot API
  description: Demo project for Spring Boot
  version: 1.0.0
  contact:
    name: chengit163
    url: https://github.com/chengit163
    email: cheng_it@163.com
# 配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis